# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-30 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='hghg',
        ),
    ]
