# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-30 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180930_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hghg',
            new_name='post',
        ),
    ]
